#Packages needed for a happy experience.

install.packages("maptools")
install.packages("raster")
install.packages("rasterVis")
install.packages("sp")
install.packages("lme4")
install.packages("rgdal")
install.packages("plyr")
install.packages("caTools")
install.packages("stringr")
install.packages("e1071")
install.packages("rjags")
install.packages("coda")
install.packages("emdbook")
install.packages("adehabitatHR")
install.packages("rgeos")
install.packages('coda')
install.packages('SDMTools')
install.packages('spatstat')
install.packages("sampSurf")
install.packages("mcmcplots")

options(repos=c(getOption('repos'), rethinking='http://xcelab.net/R'))
install.packages('rethinking',type='source')

# install.packages("ruf",repos="http://www.stat.ucla.edu/~handcock")
# install.packages("move")
install.packages("rstan", repos = "https://cloud.r-project.org/", dependencies=TRUE)
